version: '3.1'

services:

  kapitalk-nginx-container:
    container_name: 'kapitalk-nginx-container'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./kapitalk.conf:/etc/nginx/conf.d/default.conf
      - ./kapitalk-site:/usr/share/nginx/html
      - ./kapitalk-site/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/kapitalk.com/fullchain.pem:/etc/letsencrypt/live/kapitalk.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/kapitalk.com/privkey.pem:/etc/letsencrypt/live/kapitalk.com/privkey.pem
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
